### ISSUE TITLE
#Question:Video lectures

### ISSUE THREAD

**Issue by giordi91** [CIS565-Fall-2016/cis565-fall-2016.github.io#10]
Thank you for this amazing material, I love it, I was wondering if there are the video lectures avaiable somewhere? If not maybe if there is any plan to release them on coursera or youtube?
It would be a really useful resoruce.

M.

**Comment by pjcozzi** [comment]
@giordi91 thanks for the interest! We don't have recorded videos, but there is audience and slides for when I first taught the course in 2012:
* Fall: http://cis565-fall-2012.github.io/schedule.html
* Spring: http://cis565-spring-2012.github.io/schedule.html

**Comment by giordi91** [comment]
Thank you sir, I am a big e-learner, so I follow all the major website that offer serious learning material, there is not much out there about this topic, you find maybe few thing about graphich like webgl etc but nothing serious about gpgpu. I really hope at one point this lectures will be offered online either interactively as a proper course or even just avaialbe to view. 
Would be amazing if you can pass that to whoever is in charge of making such decision. Maybe if enough requests arrive they might think on it.
Best Regards

M.

**Comment by pjcozzi** [comment]
Will do @giordi91, thanks again for your interest!
